/**
 * Registry of national and international health-authority publication feeds.
 *
 * Each entry points at a feed the authority publishes itself, so the pipeline
 * reads primary sources rather than a third-party aggregator.
 *
 *   kind: 'rss'      - RSS 2.0 / RDF
 *         'atom'     - Atom 1.0
 *         'openfda'  - openFDA JSON API (api.fda.gov)
 *
 * `lat`/`lon` place the authority on the 3D globe.
 *
 * Feed endpoints move when authorities redesign their sites. Run
 * `npm run probe` from a network that can reach these hosts to see which
 * endpoints currently resolve; the admin panel shows the same health data
 * continuously once the server is running.
 */

export const SOURCES = [
  // ---------------------------------------------------------------- Americas
  {
    id: 'fda-press',
    authority: 'U.S. Food and Drug Administration',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://www.fda.gov',
    feed: 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Press announcements',
  },
  {
    id: 'fda-recalls',
    authority: 'U.S. Food and Drug Administration',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://www.fda.gov',
    feed: 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/recalls/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Recalls, market withdrawals and safety alerts',
  },
  {
    id: 'fda-medwatch',
    authority: 'U.S. Food and Drug Administration',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://www.fda.gov',
    feed: 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/medwatch/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'MedWatch safety alerts',
  },
  {
    id: 'fda-drugs',
    authority: 'U.S. Food and Drug Administration',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://www.fda.gov',
    feed: 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/drugs/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Drug approvals and guidance',
  },
  {
    id: 'fda-devices',
    authority: 'U.S. Food and Drug Administration',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://www.fda.gov',
    feed: 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/medical-devices/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Medical devices',
  },
  {
    id: 'fda-food',
    authority: 'U.S. Food and Drug Administration',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://www.fda.gov',
    feed: 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/food/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Food safety',
  },
  {
    id: 'openfda-drug-enforcement',
    authority: 'U.S. Food and Drug Administration (openFDA)',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://open.fda.gov',
    feed: 'https://api.fda.gov/drug/enforcement.json?sort=report_date:desc&limit=50',
    kind: 'openfda',
    lang: 'en',
    topic: 'Drug enforcement reports',
  },
  {
    id: 'openfda-device-enforcement',
    authority: 'U.S. Food and Drug Administration (openFDA)',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://open.fda.gov',
    feed: 'https://api.fda.gov/device/enforcement.json?sort=report_date:desc&limit=50',
    kind: 'openfda',
    lang: 'en',
    topic: 'Device enforcement reports',
  },
  {
    id: 'openfda-food-enforcement',
    authority: 'U.S. Food and Drug Administration (openFDA)',
    agency: 'FDA',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 38.9847,
    lon: -76.9819,
    site: 'https://open.fda.gov',
    feed: 'https://api.fda.gov/food/enforcement.json?sort=report_date:desc&limit=50',
    kind: 'openfda',
    lang: 'en',
    topic: 'Food enforcement reports',
  },
  {
    id: 'cdc-newsroom',
    authority: 'Centers for Disease Control and Prevention',
    agency: 'CDC',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    lat: 33.7987,
    lon: -84.3256,
    site: 'https://www.cdc.gov',
    feed: 'https://tools.cdc.gov/api/v2/resources/media/316422.rss',
    kind: 'rss',
    lang: 'en',
    topic: 'Newsroom releases',
  },
  {
    id: 'health-canada-recalls',
    authority: 'Health Canada',
    agency: 'Health Canada',
    country: 'Canada',
    countryCode: 'CA',
    region: 'North America',
    lat: 45.4215,
    lon: -75.6972,
    site: 'https://recalls-rappels.canada.ca',
    feed: 'https://recalls-rappels.canada.ca/en/feed',
    kind: 'rss',
    lang: 'en',
    topic: 'Recalls and safety alerts',
  },
  {
    id: 'health-canada-news',
    authority: 'Health Canada',
    agency: 'Health Canada',
    country: 'Canada',
    countryCode: 'CA',
    region: 'North America',
    lat: 45.4215,
    lon: -75.6972,
    site: 'https://www.canada.ca/en/health-canada.html',
    feed: 'https://api.io.canada.ca/io-server/gc/news/en/v2?dept=healthcanada&sort=publishedDate&orderBy=desc&publishedDate%3E=2020-01-01&pick=100&format=atom',
    kind: 'atom',
    lang: 'en',
    topic: 'Departmental news',
  },
  {
    id: 'anvisa',
    authority: 'Agência Nacional de Vigilância Sanitária',
    agency: 'ANVISA',
    country: 'Brazil',
    countryCode: 'BR',
    region: 'South America',
    lat: -15.7975,
    lon: -47.8919,
    site: 'https://www.gov.br/anvisa',
    feed: 'https://www.gov.br/anvisa/pt-br/assuntos/noticias-anvisa/RSS',
    kind: 'rss',
    lang: 'pt',
    topic: 'Notícias e alertas',
  },
  {
    id: 'cofepris',
    authority: 'Comisión Federal para la Protección contra Riesgos Sanitarios',
    agency: 'COFEPRIS',
    country: 'Mexico',
    countryCode: 'MX',
    region: 'North America',
    lat: 19.4326,
    lon: -99.1332,
    site: 'https://www.gob.mx/cofepris',
    feed: 'https://www.gob.mx/cofepris/articulos.rss',
    kind: 'rss',
    lang: 'es',
    topic: 'Alertas sanitarias',
  },
  {
    id: 'anmat',
    authority: 'Administración Nacional de Medicamentos, Alimentos y Tecnología Médica',
    agency: 'ANMAT',
    country: 'Argentina',
    countryCode: 'AR',
    region: 'South America',
    lat: -34.6037,
    lon: -58.3816,
    site: 'https://www.argentina.gob.ar/anmat',
    feed: 'https://www.argentina.gob.ar/anmat/comunicados.rss',
    kind: 'rss',
    lang: 'es',
    topic: 'Comunicados',
  },
  {
    id: 'invima',
    authority: 'Instituto Nacional de Vigilancia de Medicamentos y Alimentos',
    agency: 'INVIMA',
    country: 'Colombia',
    countryCode: 'CO',
    region: 'South America',
    lat: 4.711,
    lon: -74.0721,
    site: 'https://www.invima.gov.co',
    feed: 'https://www.invima.gov.co/rss/alertas.xml',
    kind: 'rss',
    lang: 'es',
    topic: 'Alertas sanitarias',
  },

  // ------------------------------------------------------------------ Europe
  {
    id: 'ema',
    authority: 'European Medicines Agency',
    agency: 'EMA',
    country: 'European Union',
    countryCode: 'EU',
    region: 'Europe',
    lat: 52.3405,
    lon: 4.9114,
    site: 'https://www.ema.europa.eu',
    feed: 'https://www.ema.europa.eu/en/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'News and press releases',
  },
  {
    id: 'ec-health',
    authority: 'European Commission - Health and Food Safety',
    agency: 'DG SANTE',
    country: 'European Union',
    countryCode: 'EU',
    region: 'Europe',
    lat: 50.8503,
    lon: 4.3517,
    site: 'https://health.ec.europa.eu',
    feed: 'https://health.ec.europa.eu/node/2/rss_en',
    kind: 'rss',
    lang: 'en',
    topic: 'Public health policy',
  },
  {
    id: 'ecdc',
    authority: 'European Centre for Disease Prevention and Control',
    agency: 'ECDC',
    country: 'European Union',
    countryCode: 'EU',
    region: 'Europe',
    lat: 59.3293,
    lon: 18.0686,
    site: 'https://www.ecdc.europa.eu',
    feed: 'https://www.ecdc.europa.eu/en/taxonomy/term/1532/feed',
    kind: 'rss',
    lang: 'en',
    topic: 'Threat assessments and news',
  },
  {
    id: 'mhra',
    authority: 'Medicines and Healthcare products Regulatory Agency',
    agency: 'MHRA',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    lat: 51.4975,
    lon: -0.1357,
    site: 'https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency',
    feed: 'https://www.gov.uk/search/all.atom?organisations%5B%5D=medicines-and-healthcare-products-regulatory-agency',
    kind: 'atom',
    lang: 'en',
    topic: 'Publications, alerts and guidance',
  },
  {
    id: 'mhra-drug-safety',
    authority: 'MHRA - Drug Safety Update',
    agency: 'MHRA',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    lat: 51.4975,
    lon: -0.1357,
    site: 'https://www.gov.uk/drug-safety-update',
    feed: 'https://www.gov.uk/drug-safety-update.atom',
    kind: 'atom',
    lang: 'en',
    topic: 'Drug Safety Update bulletin',
  },
  {
    id: 'swissmedic',
    authority: 'Swissmedic',
    agency: 'Swissmedic',
    country: 'Switzerland',
    countryCode: 'CH',
    region: 'Europe',
    lat: 46.948,
    lon: 7.4474,
    site: 'https://www.swissmedic.ch',
    feed: 'https://www.swissmedic.ch/swissmedic/en/home/_jcr_content.feed',
    kind: 'rss',
    lang: 'en',
    topic: 'News and safety information',
  },
  {
    id: 'bfarm',
    authority: 'Bundesinstitut für Arzneimittel und Medizinprodukte',
    agency: 'BfArM',
    country: 'Germany',
    countryCode: 'DE',
    region: 'Europe',
    lat: 50.7374,
    lon: 7.0982,
    site: 'https://www.bfarm.de',
    feed: 'https://www.bfarm.de/SiteGlobals/Functions/RSSFeed/DE/RSSNewsfeed/RSSNewsfeed.xml',
    kind: 'rss',
    lang: 'de',
    topic: 'Aktuelle Meldungen',
  },
  {
    id: 'pei',
    authority: 'Paul-Ehrlich-Institut',
    agency: 'PEI',
    country: 'Germany',
    countryCode: 'DE',
    region: 'Europe',
    lat: 49.9929,
    lon: 8.2473,
    site: 'https://www.pei.de',
    feed: 'https://www.pei.de/SiteGlobals/Functions/RSSFeed/DE/RSSNewsfeed/rss-newsfeed.xml',
    kind: 'rss',
    lang: 'de',
    topic: 'Vaccines and biomedicines',
  },
  {
    id: 'ansm',
    authority: 'Agence nationale de sécurité du médicament',
    agency: 'ANSM',
    country: 'France',
    countryCode: 'FR',
    region: 'Europe',
    lat: 48.8566,
    lon: 2.3522,
    site: 'https://ansm.sante.fr',
    feed: 'https://ansm.sante.fr/rss/actualites.xml',
    kind: 'rss',
    lang: 'fr',
    topic: 'Actualités et alertes',
  },
  {
    id: 'aifa',
    authority: 'Agenzia Italiana del Farmaco',
    agency: 'AIFA',
    country: 'Italy',
    countryCode: 'IT',
    region: 'Europe',
    lat: 41.9028,
    lon: 12.4964,
    site: 'https://www.aifa.gov.it',
    feed: 'https://www.aifa.gov.it/web/guest/rss',
    kind: 'rss',
    lang: 'it',
    topic: 'Comunicati e allerte',
  },
  {
    id: 'aemps',
    authority: 'Agencia Española de Medicamentos y Productos Sanitarios',
    agency: 'AEMPS',
    country: 'Spain',
    countryCode: 'ES',
    region: 'Europe',
    lat: 40.4168,
    lon: -3.7038,
    site: 'https://www.aemps.gob.es',
    feed: 'https://www.aemps.gob.es/feed/',
    kind: 'rss',
    lang: 'es',
    topic: 'Notas informativas',
  },
  {
    id: 'hpra',
    authority: 'Health Products Regulatory Authority',
    agency: 'HPRA',
    country: 'Ireland',
    countryCode: 'IE',
    region: 'Europe',
    lat: 53.3498,
    lon: -6.2603,
    site: 'https://www.hpra.ie',
    feed: 'https://www.hpra.ie/rss/news',
    kind: 'rss',
    lang: 'en',
    topic: 'Safety notices',
  },
  {
    id: 'cbg-meb',
    authority: 'Medicines Evaluation Board',
    agency: 'CBG-MEB',
    country: 'Netherlands',
    countryCode: 'NL',
    region: 'Europe',
    lat: 52.0907,
    lon: 5.1214,
    site: 'https://english.cbg-meb.nl',
    feed: 'https://english.cbg-meb.nl/rss/news',
    kind: 'rss',
    lang: 'en',
    topic: 'Medicines evaluation news',
  },
  {
    id: 'lakemedelsverket',
    authority: 'Läkemedelsverket (Swedish Medical Products Agency)',
    agency: 'MPA',
    country: 'Sweden',
    countryCode: 'SE',
    region: 'Europe',
    lat: 59.8586,
    lon: 17.6389,
    site: 'https://www.lakemedelsverket.se',
    feed: 'https://www.lakemedelsverket.se/en/rss/news',
    kind: 'rss',
    lang: 'en',
    topic: 'News and safety',
  },
  {
    id: 'dkma',
    authority: 'Danish Medicines Agency',
    agency: 'DKMA',
    country: 'Denmark',
    countryCode: 'DK',
    region: 'Europe',
    lat: 55.6761,
    lon: 12.5683,
    site: 'https://laegemiddelstyrelsen.dk',
    feed: 'https://laegemiddelstyrelsen.dk/en/rss/',
    kind: 'rss',
    lang: 'en',
    topic: 'News',
  },
  {
    id: 'fimea',
    authority: 'Finnish Medicines Agency',
    agency: 'Fimea',
    country: 'Finland',
    countryCode: 'FI',
    region: 'Europe',
    lat: 60.1699,
    lon: 24.9384,
    site: 'https://www.fimea.fi',
    feed: 'https://www.fimea.fi/web/en/-/asset_publisher/rss',
    kind: 'rss',
    lang: 'en',
    topic: 'News',
  },
  {
    id: 'noma',
    authority: 'Norwegian Medical Products Agency',
    agency: 'NoMA',
    country: 'Norway',
    countryCode: 'NO',
    region: 'Europe',
    lat: 59.9139,
    lon: 10.7522,
    site: 'https://www.dmp.no',
    feed: 'https://www.dmp.no/rss/nyheter',
    kind: 'rss',
    lang: 'no',
    topic: 'Nyheter',
  },
  {
    id: 'famhp',
    authority: 'Federal Agency for Medicines and Health Products',
    agency: 'FAMHP',
    country: 'Belgium',
    countryCode: 'BE',
    region: 'Europe',
    lat: 50.8503,
    lon: 4.3517,
    site: 'https://www.famhp.be',
    feed: 'https://www.famhp.be/en/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'News and alerts',
  },
  {
    id: 'titck',
    authority: 'Türkiye İlaç ve Tıbbi Cihaz Kurumu',
    agency: 'TİTCK',
    country: 'Türkiye',
    countryCode: 'TR',
    region: 'Europe',
    lat: 39.9334,
    lon: 32.8597,
    site: 'https://www.titck.gov.tr',
    feed: 'https://www.titck.gov.tr/rss',
    kind: 'rss',
    lang: 'tr',
    topic: 'Duyurular',
  },

  // ------------------------------------------------- Asia-Pacific and Oceania
  {
    id: 'tga',
    authority: 'Therapeutic Goods Administration',
    agency: 'TGA',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Oceania',
    lat: -35.2809,
    lon: 149.13,
    site: 'https://www.tga.gov.au',
    feed: 'https://www.tga.gov.au/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Safety alerts and news',
  },
  {
    id: 'medsafe',
    authority: 'Medsafe',
    agency: 'Medsafe',
    country: 'New Zealand',
    countryCode: 'NZ',
    region: 'Oceania',
    lat: -41.2865,
    lon: 174.7762,
    site: 'https://www.medsafe.govt.nz',
    feed: 'https://www.medsafe.govt.nz/rss/AlertsRSS.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Safety alerts',
  },
  {
    id: 'pmda',
    authority: 'Pharmaceuticals and Medical Devices Agency',
    agency: 'PMDA',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Asia',
    lat: 35.6762,
    lon: 139.6503,
    site: 'https://www.pmda.go.jp/english/',
    feed: 'https://www.pmda.go.jp/rss/english.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Safety information',
  },
  {
    id: 'mfds',
    authority: 'Ministry of Food and Drug Safety',
    agency: 'MFDS',
    country: 'South Korea',
    countryCode: 'KR',
    region: 'Asia',
    lat: 36.4801,
    lon: 127.2891,
    site: 'https://www.mfds.go.kr/eng/',
    feed: 'https://www.mfds.go.kr/eng/rss/news.do',
    kind: 'rss',
    lang: 'en',
    topic: 'Press releases',
  },
  {
    id: 'hsa',
    authority: 'Health Sciences Authority',
    agency: 'HSA',
    country: 'Singapore',
    countryCode: 'SG',
    region: 'Asia',
    lat: 1.3521,
    lon: 103.8198,
    site: 'https://www.hsa.gov.sg',
    feed: 'https://www.hsa.gov.sg/rss/announcements',
    kind: 'rss',
    lang: 'en',
    topic: 'Announcements and recalls',
  },
  {
    id: 'cdsco-india',
    authority: 'Central Drugs Standard Control Organisation (via PIB Health)',
    agency: 'CDSCO',
    country: 'India',
    countryCode: 'IN',
    region: 'Asia',
    lat: 28.6139,
    lon: 77.209,
    site: 'https://cdsco.gov.in',
    feed: 'https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3',
    kind: 'rss',
    lang: 'en',
    topic: 'Health ministry releases',
  },
  {
    id: 'fda-philippines',
    authority: 'Food and Drug Administration Philippines',
    agency: 'FDA PH',
    country: 'Philippines',
    countryCode: 'PH',
    region: 'Asia',
    lat: 14.5995,
    lon: 120.9842,
    site: 'https://www.fda.gov.ph',
    feed: 'https://www.fda.gov.ph/feed/',
    kind: 'rss',
    lang: 'en',
    topic: 'Advisories and circulars',
  },
  {
    id: 'npra-malaysia',
    authority: 'National Pharmaceutical Regulatory Agency',
    agency: 'NPRA',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Asia',
    lat: 3.139,
    lon: 101.6869,
    site: 'https://www.npra.gov.my',
    feed: 'https://www.npra.gov.my/index.php/en/?format=feed&type=rss',
    kind: 'rss',
    lang: 'en',
    topic: 'Announcements',
  },
  {
    id: 'tfda-taiwan',
    authority: 'Taiwan Food and Drug Administration',
    agency: 'TFDA',
    country: 'Taiwan',
    countryCode: 'TW',
    region: 'Asia',
    lat: 25.033,
    lon: 121.5654,
    site: 'https://www.fda.gov.tw/ENG/',
    feed: 'https://www.fda.gov.tw/ENG/rss.aspx',
    kind: 'rss',
    lang: 'en',
    topic: 'News',
  },
  {
    id: 'hk-drug-office',
    authority: 'Department of Health - Drug Office',
    agency: 'DH Hong Kong',
    country: 'Hong Kong SAR',
    countryCode: 'HK',
    region: 'Asia',
    lat: 22.3193,
    lon: 114.1694,
    site: 'https://www.drugoffice.gov.hk',
    feed: 'https://www.drugoffice.gov.hk/eps/rss/news/en',
    kind: 'rss',
    lang: 'en',
    topic: 'Drug safety news',
  },

  // ------------------------------------------------ Middle East and Africa
  {
    id: 'sfda-saudi',
    authority: 'Saudi Food and Drug Authority',
    agency: 'SFDA',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    region: 'Middle East',
    lat: 24.7136,
    lon: 46.6753,
    site: 'https://www.sfda.gov.sa',
    feed: 'https://www.sfda.gov.sa/en/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'News and recalls',
  },
  {
    id: 'sahpra',
    authority: 'South African Health Products Regulatory Authority',
    agency: 'SAHPRA',
    country: 'South Africa',
    countryCode: 'ZA',
    region: 'Africa',
    lat: -25.7479,
    lon: 28.2293,
    site: 'https://www.sahpra.org.za',
    feed: 'https://www.sahpra.org.za/feed/',
    kind: 'rss',
    lang: 'en',
    topic: 'News and safety updates',
  },
  {
    id: 'nafdac',
    authority: 'National Agency for Food and Drug Administration and Control',
    agency: 'NAFDAC',
    country: 'Nigeria',
    countryCode: 'NG',
    region: 'Africa',
    lat: 9.0765,
    lon: 7.3986,
    site: 'https://nafdac.gov.ng',
    feed: 'https://nafdac.gov.ng/feed/',
    kind: 'rss',
    lang: 'en',
    topic: 'Public alerts',
  },

  // ------------------------------------------------------------ International
  {
    id: 'who-news',
    authority: 'World Health Organization',
    agency: 'WHO',
    country: 'International',
    countryCode: 'INT',
    region: 'Global',
    lat: 46.2324,
    lon: 6.1365,
    site: 'https://www.who.int',
    feed: 'https://www.who.int/rss-feeds/news-english.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'News releases',
  },
  {
    id: 'who-don',
    authority: 'WHO - Disease Outbreak News',
    agency: 'WHO',
    country: 'International',
    countryCode: 'INT',
    region: 'Global',
    lat: 46.2324,
    lon: 6.1365,
    site: 'https://www.who.int/emergencies/disease-outbreak-news',
    feed: 'https://www.who.int/feeds/entity/csr/don/en/rss.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Disease outbreak news',
  },
  {
    id: 'who-alerts',
    authority: 'WHO - Medical Product Alerts',
    agency: 'WHO',
    country: 'International',
    countryCode: 'INT',
    region: 'Global',
    lat: 46.2324,
    lon: 6.1365,
    site: 'https://www.who.int/teams/regulation-prequalification/incidents-and-SF/full-list-of-who-medical-product-alerts',
    feed: 'https://www.who.int/rss-feeds/medical-product-alerts-english.xml',
    kind: 'rss',
    lang: 'en',
    topic: 'Falsified and substandard products',
  },
  {
    id: 'ich',
    authority: 'International Council for Harmonisation',
    agency: 'ICH',
    country: 'International',
    countryCode: 'INT',
    region: 'Global',
    lat: 46.2044,
    lon: 6.1432,
    site: 'https://www.ich.org',
    feed: 'https://www.ich.org/feed.rss',
    kind: 'rss',
    lang: 'en',
    topic: 'Harmonisation guidelines',
  },
  {
    id: 'edqm',
    authority: 'European Directorate for the Quality of Medicines',
    agency: 'EDQM',
    country: 'International',
    countryCode: 'INT',
    region: 'Europe',
    lat: 48.5734,
    lon: 7.7521,
    site: 'https://www.edqm.eu',
    feed: 'https://www.edqm.eu/en/rss',
    kind: 'rss',
    lang: 'en',
    topic: 'Pharmacopoeia and standards',
  },
];

export const REGIONS = [...new Set(SOURCES.map((s) => s.region))].sort();

export const sourceById = new Map(SOURCES.map((s) => [s.id, s]));
